### ISSUE TITLE
dsp global map?

### ISSUE THREAD

**Issue by anja-sheppard** [tud-amr/semantic_dsp_map#1]
Hi, I'm looking to use this method for a comparison but I cannot find the `dsp_global_map` repo mentioned in the static semantic mapping mode instructions. Will that be provided sometime soon? Is there a workaround for constructing a global map in static mode?

Thanks!

**Comment by g-ch** [comment]
Thank you for your interest in the semantic DSP map. The dsp_global_map code for static mapping is indeed in a separate repo. I made it public just now so that you can use it. 

https://github.com/g-ch/dsp_global_mapping  

There is no readme for this repo yet but running the launch file should work. I will test it and add a readme file.

**Comment by g-ch** [comment]
Hi, @anja-sheppard 
I have updated the readme file of [dsp global mapping](https://github.com/g-ch/dsp_global_mapping) and also added some detailed description of the [custom input message/data structure](https://github.com/tud-amr/semantic_dsp_map/blob/main/docs/custom_files.md) of the Semantic DSP Map. This might be helpful.
